---
title: "GSE118614 10x"
output: html_notebook
---

This is an analysis for the dataset [GSE118614](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE118614) made available by Clark BS et al. in their paper [_Single-cell RNA-Seq Analysis of Retinal Development Identifies NFI Factors as Regulating Mitotic Exit and Late-Born Cell Specification_](https://www.sciencedirect.com/science/article/abs/pii/S0896627319303459).



```{r}
rm(list=ls())
gc()

library(Matrix)
library(ggplot2)
library(Rtsne)
library(matrixStats)

temp = readRDS('../data/gse118614_10x_30k.RDS')
mat = temp[[1]]
barcode.names = temp[[2]]
feature.names = temp[[3]]

rm(temp)
gc()
```

```{r}
table(barcode.names$sample)
```

```{r}
mask <- barcode.names$umap2_CellType != "Doublets"
mat <- mat[mask, ]
barcode.names <- barcode.names[mask, ]
gc()
```

```{r}
set.seed(0)

mask = rep(FALSE, dim(mat)[1])
plate = c('E11', 'E12_rep1', 'E14_rep1', 'E14_rep2', 'E16', 'E18_rep2', 'E18_rep3', 'P0', 'P14', 'P2_rep2', 'P2_rep3', 'P5', 'P8_rep1', 'P8_rep2')
num = c(400, 400, 200, 200, 400, 200, 200, 400, 400, 200, 200, 400, 200, 200)

mask = c()

for (i in 1:length(plate)){
  mask <- c(mask, 
            sample((1:dim(mat)[1])[barcode.names$sample == plate[i]], num[i]))
}

length(mask)
```

```{r}
mat <- mat[mask, ]
barcode.names <- barcode.names[mask, ]
gc()
```

```{r}
mat <- as.matrix(mat)
```

```{r}
barcode.names$umap2_CellType[barcode.names$umap2_CellType == 'RPE/Margin/Periocular Mesenchyme/Lens Epithelial Cells'] <- '[#] Other rare cells' 

photo <- c('Cones', 'Rods', 'Photoreceptor Precursors')
barcode.names$umap2_CellType[barcode.names$umap2_CellType %in% photo] = paste('[P]', barcode.names$umap2_CellType[barcode.names$umap2_CellType %in% photo])

neural <- c('Bipolar Cells', 'Amacrine Cells', 'Horizontal Cells', 'Neurogenic Cells', 'Retinal Ganglion Cells')
barcode.names$umap2_CellType[barcode.names$umap2_CellType %in% neural] = paste('[N]', barcode.names$umap2_CellType[barcode.names$umap2_CellType %in% neural])

progenitor <- c('Late RPCs', 'Early RPCs')
barcode.names$umap2_CellType[barcode.names$umap2_CellType %in% progenitor] = paste('[G]', barcode.names$umap2_CellType[barcode.names$umap2_CellType %in% progenitor])

glia <- c('Muller Glia')
barcode.names$umap2_CellType[barcode.names$umap2_CellType %in% glia] = paste('[M]', barcode.names$umap2_CellType[barcode.names$umap2_CellType %in% glia])
```


```{r}
table(barcode.names$age)
table(barcode.names$sample)
table(barcode.names$umap2_CellType)
table(barcode.names$age, barcode.names$umap2_CellType)
table(barcode.names$sample, barcode.names$umap2_CellType)
```

```{r}
head(feature.names)
```

```{r}
head(barcode.names)
```

```{r}
colnames(mat) <- feature.names$id
rownames(mat) <- rownames(barcode.names)
```


```{r}
source("../R/varactor.R")
```

```{r}
obj <- Varactor$new(data = list(expr=t(mat)), 
                    labels = list(expr = list(plate = barcode.names$sample, type=barcode.names$umap2_CellType, age=barcode.names$age)), 
                    what = 'raw')

obj$normalize()
#obj$normalized <- obj$raw
obj$combine(sd_threshold = 0.0, cv_threshold = 0.5)
dim(obj$combined)
obj$reduce(reduce_dim = 50)
obj$clean()
```

```{r}
set.seed(0)
obj$define_metric("primary", "euclidean")$measure("primary")$embed("primary", "tsne")
obj$plot("primary", "embedding", "type")
obj$plot("primary", "embedding", "plate")
obj$plot("primary", "embedding", "age")
```


```{r}
set.seed(0)
obj$define_metric("alternative", "davidson", strata = 'plate')$measure("alternative")$embed("alternative", "tsne")
obj$plot("alternative", "embedding", "type")
obj$plot("alternative", "embedding", "plate")
obj$plot("alternative", "embedding", "age")

obj$labels$type2 <- obj$labels$type
obj$labels$type2[obj$labels$type2 %in% c('Early RPCs', 'Intermediate RPCs', 'Late RPCs')] = 'RPCs'
obj$plot("alternative", "embedding", "type2")
```

```{r}
set.seed(0)
obj$embed("primary", "umap")
obj$plot("primary", "embedding", "type")
obj$plot("primary", "embedding", "plate")
obj$plot("primary", "embedding", "age")
```

```{r}
set.seed(0)
obj$embed("alternative", "umap")
obj$plot("alternative", "embedding", "type")
obj$plot("alternative", "embedding", "plate")
obj$plot("alternative", "embedding", "age")

obj$labels$type2 <- obj$labels$type
obj$labels$type2[obj$labels$type2 %in% c('Early RPCs', 'Intermediate RPCs', 'Late RPCs')] = 'RPCs'
obj$plot("alternative", "embedding", "type2")
```

```{r}

```

