---
title: "Alternative clustering for normal cells in the Melanoma dataset"
output: html_notebook
---
 
```{r}
rm(list=ls())
library(matrixStats)
library(Rtsne)
library(dplyr)
library(ggplot2)
library(expm)
library(RColorBrewer)
```

```{r}
data <- readRDS('../data/raw/lake.rds')
```

```{r}
dim(data)
data[1:5, 1:5]
```

```{r}
expr_matrix <- data@assays$data$logcounts
expr_matrix <- expr_matrix

mask <- rowSds(expr_matrix) > 0
expr_matrix <- expr_matrix[mask, ]

expr_matrix <- expr_matrix / rowSds(expr_matrix)
dim(expr_matrix)
```

```{r}
head(data@colData)
table(data@colData$Source)
table(data@colData$cell_type1)
table(data@colData$batch)
table(data@colData$Plate)
```


```{r}
patient_labels <- data@colData$batch
type_labels <- data@colData$cell_type1
location_labels <- data@colData$Source
plate_labels <- data@colData$Plate
```

```{r}
sum(is.na(patient_labels))
sum(is.na(type_labels))
sum(is.na(location_labels))
```

```{r}
source("../R/varactor.R")

obj <- Varactor$new(data = list(expr=expr_matrix), 
                    labels = list(expr = list(patient = as.character(patient_labels),
                                              type = as.character(type_labels),
                                              plate = as.character(data@colData$Plate),
                                              location = as.character(location_labels))), 
                    what = 'raw')

obj$normalize()
#obj$normalized <- obj$raw
obj$combine(sd_threshold = 0.5, cv_threshold = 0.5)
dim(obj$combined)
obj$reduce(reduce_dim = 50)
obj$clean()
```

```{r}
set.seed(0)
obj$define_metric("primary", "euclidean")$measure("primary")$embed("primary", "tsne")
obj$plot("primary", "embedding", "type")
obj$plot("primary", "embedding", "plate")
obj$plot("primary", "embedding", "patient")
```


```{r}
obj$embed("primary", "umap")
obj$plot("primary", "embedding", "type")
obj$plot("primary", "embedding", "plate")
obj$plot("primary", "embedding", "patient")
```

```{r}
set.seed(0)
obj$define_metric("alternative", "davidson", strata = "patient")$measure("alternative")$embed("alternative", "tsne")
obj$plot("alternative", "embedding", "type")
obj$plot("alternative", "embedding", "plate")
obj$plot("alternative", "embedding", "patient")
```

```{r}
obj$embed("alternative", "umap")
obj$plot("alternative", "embedding", "type")
obj$plot("alternative", "embedding", "plate")
obj$plot("alternative", "embedding", "patient")
```


```{r}

```

