---
title: "GSE118614 10x"
output: html_notebook
---

This is an analysis for the dataset [GSE118614](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE118614) made available by Clark BS et al. in their paper [_Single-cell RNA-Seq Analysis of Retinal Development Identifies NFI Factors as Regulating Mitotic Exit and Late-Born Cell Specification_](https://www.sciencedirect.com/science/article/abs/pii/S0896627319303459).



```{r}
rm(list=ls())
gc()
library(Matrix)
library(Seurat)
```


```{r}
library(clusterCrit)
```

# Overview of the dataset
We first overview the dataset.

```{r}
#data <- read.csv("../data/miller20/expr.csv")
#rownames(data) <- data$index
#data <- data[-1]
#data <- as.matrix(data)
```

```{r}
#saveRDS(object = data, file = "data.RDS")
```

```{r}
data <- readRDS("data.RDS")
```

```{r}
meta.data <- read.csv("../data/miller20/meta.data.csv", row.names = 1)
```

```{r}
obj <- CreateSeuratObject(t(data), meta.data = meta.data)
```

```{r}
rm(data)
gc()
```

```{r}
obj
```

```{r}
table(obj$Cell_type)
```

```{r}
table(obj$Age)
```

```{r}
table(obj$Sample)
```

```{r}
objs <- SplitObject(obj, split.by = "Sample")
```

```{r}
rm(obj)
gc()
```


```{r}
for (i in names(objs)) {
  objs[[i]] <- NormalizeData(objs[[i]], verbose=FALSE)
  objs[[i]] <- FindVariableFeatures(objs[[i]], selection.method = "vst", nfeatures = 2000, verbose=FALSE)

  objs[[i]] <- ScaleData(objs[[i]], verbose=FALSE)
  objs[[i]] <- RunPCA(objs[[i]], features = VariableFeatures(object = objs[[i]]), verbose=FALSE)
}

ptm = proc.time()
anchors <- FindIntegrationAnchors(object.list = objs, dims = 1:30)
obj <- IntegrateData(anchorset = anchors, dims = 1:30)
proc.time() - ptm
```

```{r}
obj <- ScaleData(obj, verbose = FALSE)
obj <- RunPCA(obj, npcs = 30, verbose = FALSE)
```

```{r}
obj <- RunUMAP(obj, dims = 1:30, verbose=FALSE)
```

```{r}
saveRDS(obj, "lung_seurat.RDS")
```

```{r}
#obj <- readRDS("lung_seurat.RDS")
```


```{r}
DimPlot(obj, reduction = "umap", group.by = "Cell_group", label = T, repel=T, label.size = 5,  pt.size = 0) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        text=element_text(size=18))
ggsave("lung_seurat_group.pdf")

DimPlot(obj, reduction = "umap", group.by = "Cell_group", label = T, repel=T, label.size = 8,  pt.size = 0) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        text=element_text(size=30))
ggsave("lung_seurat_group.png", height=12, width=18, dpi = 100)
```

```{r fig.height=8, fig.width=18}
DimPlot(obj, reduction = "umap", group.by = "Cell_type", label = T, repel=T, label.size = 4,  pt.size = 0) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        text=element_text(size=18))
ggsave("lung_seurat_label.pdf")
```


```{r}
DimPlot(obj, reduction = "umap", group.by = "Sample", label.size = 5,  pt.size = 0) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        text=element_text(size=18))
ggsave("lung_seurat_sample.pdf")

p<-DimPlot(obj, reduction = "umap", group.by = "Sample", label.size = 12,  pt.size = 0) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        text=element_text(size=30))
ggsave("lung_seurat_sample.png", height=12, width=18, dpi = 100)
```

